### ISSUE TITLE
[BUG] According to the first step of Javascript Reference, an error is reported

### ISSUE THREAD

**Issue by ahaocoder** [sei-protocol/sei-js#108] opened 2023-12-25 07:50 UTC
**SeiJS package & version**
    "@sei-js/core": "^3.1.2",
    "@sei-js/proto": "^3.1.0",
    "@sei-js/react": "^3.2.0", 

**Describe the bug**
According to the first step of Javascript Reference, an error is reported
npm install core/react/proto
ERROR in ./node_modules/@cosmjs/crypto/build/pbkdf2.js 50:67-84
Module not found: Error: Can't resolve 'crypto' in '/Users/ahao/WebstormProjects/sei-react/node_modules/@cosmjs/crypto/build'

The following are some screenshots：
![image](https://github.com/sei-protocol/sei-js/assets/142813664/7d445af1-1f0f-4ef0-bdba-990a816ae98a)
![image](https://github.com/sei-protocol/sei-js/assets/142813664/d4559476-84a5-46d6-aa21-cfd3648a219d)
![image](https://github.com/sei-protocol/sei-js/assets/142813664/a5fa74dd-3438-4bd6-8af2-4351b0646545)

**Comment by besated** [comment] 2023-12-30 00:08
Hey @ahaocoder, could you provide a small code snippet or a sample project that reproduces the issue? This will be helpful for us to see exactly what's going wrong. Also, which bundler are you using? The suggested bundler in our docs is Vite. 

From the logs, it looks like you're using webpack (>5), which doesn't include the crypto polyfill by default. So, you'll likely need to add something like https://github.com/Richienb/node-polyfill-webpack-plugin

**Comment by besated** [comment] 2024-02-01 22:07
Closing for now. Feel free to reopen if you have more details!

**Closed by besated** 2024-02-01 22:07 UTC
Labels: bug, linear
